version: '3.8'

services:
  postgres:
    image: postgres:10.3
    restart: always
    container_name: new-online-store
    environment:
      - POSTGRES_DB=new-online-store
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: